name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r microservices/service1/requirements.txt
        pip install -r microservices/service2/requirements.txt
        pip install flake8 pytest

    - name: Verify dependencies
      run: pip check

    - name: Lint Service 1
      run: flake8 microservices/service1/
      continue-on-error: false

    - name: Lint Service 2
      run: flake8 microservices/service2/
      continue-on-error: false

    - name: Test Service 1
      working-directory: ./microservices/service1
      run:  python -m pytest tests/

    - name: Test Service 2
      working-directory: ./microservices/service2
      run: python -m pytest tests/
